baseurl = "https://simonstorlschulke.github.io/Datenverarbeitung-in-der-Medienproduktion/public/"
languageCode = "de"
title = "Datenverarbeitung in der Medienproduktion"
theme = "material-docs"
metadataformat = "yaml"
canonifyurls = true
home = "general/"

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	description = "Online-Material zur Veranstaltung Datenverarbeitung in der Medienproduktion."

	logo = "images/lecture_logo_dvmp.png"
	favicon = "images/lecture_icon.png"

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/custom.css"]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "lime"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[[menu.main]]
	name   = "Allgemeines"

[[menu.main]]
	name   = "Kursinfo"
	url    = "general/"
	parent = "Allgemeines"

[[menu.main]]
	name   = "Links & Literatur"
	url    = "links/"
	parent = "Allgemeines"

[[menu.main]]
	name   = "Python Style Guide"
	url    = "python-style-guide/"
	parent = "Allgemeines"

[[menu.main]]
	name   = "Kapitel"

[[menu.main]]
	name   = "1. Blender & Scripting-Tools"
	url    = "chapter01/exercise01_a/"
	parent = "Kapitel"

[[menu.main]]
	name   = "2. Python & Blender API"
	url    = "chapter02/exercise01_a/"
	parent = "Kapitel"

[[menu.main]]
	name   = "3. Operatoren & Codestruktur"
	url    = "chapter03/exercise01_a/"
	parent = "Kapitel"

[[menu.main]]
	name   = "4. Meshes - Basics "
	url    = "chapter04/exercise01_a/"
	parent = "Kapitel"

[[menu.main]]
	name   = "5. Meshes - BMesh"
	url    = "chapter05/exercise01_a/"
	parent = "Kapitel"

[[menu.main]]
	name   = "6 Addon-Entwicklung und VS Code"
	url    = "chapter06/exercise01_a/"
	parent = "Kapitel"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false