baseurl = "https://simonstorlschulke.github.io/Datenverarbeitung-in-der-Medienproduktion/public/"
languageCode = "de"
title = "Datenverarbeitung in der Medienproduktion"
theme = "material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	description = "Online-Material zur Veranstaltung Datenverarbeitung in der Medienproduktion."

	logo = "images/lecture_logo_dvmp.png"
	favicon = "images/lecture_icon.png"

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/custom.css"]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "lime"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
	name   = "Allgemeines"
	url    = "general/"
	weight = 10

[[menu.main]]
	name   = "Kapitel 1"
	weight = 20

[[menu.main]]
	name   = "1.1 - Monkeygrid"
	url    = "chapter01/exercise01_a/"
	weight = 21
	parent = "Kapitel 1"


[[menu.main]]
	name   = "Kapitel 2"
	weight = 30

[[menu.main]]
	name   = "2.1 - Intro"
	url    = "chapter02/exercise01_a/"
	weight = 31
	parent = "Kapitel 2"

[[menu.main]]
	name   = "Kapitel 3"
	weight = 40

[[menu.main]]
	name   = "3.1 - Würfeldimension"
	url    = "chapter03/exercise01_a/"
	weight = 41
	parent = "Kapitel 3"

[[menu.main]]
	name   = "Kapitel 4"
	weight = 50

[[menu.main]]
	name   = "4.1 - Meshgenerierung"
	url    = "chapter04/exercise01_a/"
	weight = 51
	parent = "Kapitel 4"

[[menu.main]]
	name   = "FELIX"
	weight = 997

[[menu.main]]
	name   = "Ergebnisse einreichen"
	url    = "KURSLINK EINFÜGEN"
	weight = 998
	parent = "FELIX"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
