baseurl = "https://simonstorlschulke.github.io/Datenverarbeitung-in-der-Medienproduktion/public/"
languageCode = "de"
title = "Datenverarbeitung in der Medienproduktion"
theme = "material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	description = "Online-Material zur Veranstaltung Datenverarbeitung in der Medienproduktion."

	logo = "images/lecture_logo_dvmp.png"
	favicon = "images/lecture_icon.png"

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/custom.css"]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "lime"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[[menu.main]]
	name   = "Allgemeines"
	url    = "general/"
	weight = 10

[[menu.main]]
	name   = "Kapitel"
	weight = 20

[[menu.main]]
	name   = "1. Blender & Dev-Tools"
	url    = "chapter01/exercise01_a/"
	weight = 21
	parent = "Kapitel"

[[menu.main]]
	name   = "2. Python & Blender API"
	url    = "chapter02/exercise01_a/"
	weight = 31
	parent = "Kapitel"

[[menu.main]]
	name   = "3. Operatoren & Codestruktur"
	url    = "chapter03/exercise01_a/"
	weight = 41
	parent = "Kapitel"

[[menu.main]]
	name   = "4. Meshgenerierung 1 "
	url    = "chapter04/exercise01_a/"
	weight = 51
	parent = "Kapitel"

[[menu.main]]
	name   = "5. Meshgenerierung 2 - BMesh"
	url    = "chapter05/exercise01_a/"
	weight = 51
	parent = "Kapitel"

[[menu.main]]
	name   = "6 Addon-Entwicklung und VS Code"
	url    = "chapter06/exercise01_a/"
	weight = 51
	parent = "Kapitel"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
